### ISSUE TITLE
Carte per il briscolone

### ISSUE THREAD

**Issue by Trainax** [ProfAndreaPollini/profandreapollini-youtube-videos#21]
Trovare delle carte per il gioco del briscolone con licenza CC0

**Comment by ProfAndreaPollini** [comment]
thanks  @tetofonta

https://kelbet.it/wp-content/uploads/2014/01/Carte_napoletane_al_completo.jpg

**Comment by Trainax** [comment]
Le carte sono state trovate. Ringraziamo il collaboratore
