### ISSUE TITLE
Video sui design pattern proxy

### ISSUE THREAD

**Issue by fedemelis** [ProfAndreaPollini/profandreapollini-youtube-videos#97]
# Description of the idea:

# Resources (web pages, video, PDF links):

# Programming language (if known or relevant):
- [ ] Python
- [ ] Javascript
- [ ] C
- [ ] C++
- [ ] Flutter
- [x] Java
- [ ] Other (explain below) 

# Notes:

**Comment by ProfAndreaPollini** [comment]
ho caricato ieri il pattern command, il prossimo sará il proxy!
